### PR TITLE
Consider resources in flavor sources sets

### PR DESCRIPTION
**Pull request by kkris**
When a product flavor overrides resources, they are currently not picked up by the plugin.

This PR includes the source set names of all defined product flavors and also extends `samle/example-custom` with some overriden icons to test.

Steps to reproduce before the fix: build via `example-custom:installStagingAaaDebug` and observe that the app icon used is from the `main` source set which has lower priority than `staging`

After the fix, the correct icons from `staging/res` are picked up.

Note: I had to use `--rerun-tasks` at times since the task does not always run, depending on the changes made since the last execution.

### CODE REVIEW

**Comment by mateuszkwiecinski** [comment]
Thanks! I'll try to take a look soon :) (I can also record new screenshots if they fail, since that's _unconvenient_ for most people:/ ) 

>Note: I had to use `--rerun-tasks` at times since the task does not always run, depending on the changes made since the last execution.

Can you clarify which tasks did you have problems with? Which tasks you expected to run and which were up-to-date (or from-cache?)?

Also, I wanted to let you know to ignore optional failing checks - I'm still working on restoring build's configuration-cache compatibility :)

**Comment by kkris** [comment]
> Thanks! I'll try to take a look soon :) (I can also record new screenshots if they fail, since that's _unconvenient_ for most people:/ )

Thanks! I tried to run the `recordAll` task, but it failed with this error: `Failed to create the directory /sdcard/screenshots/com.example.flavor.productionAaaDebug.test/screenshots-default for screenshots. Is your sdcard directory read-only?`. Are there any other preconditions I need to fulfill?

> > Note: I had to use `--rerun-tasks` at times since the task does not always run, depending on the changes made since the last execution.
> 
> Can you clarify which tasks did you have problems with? Which tasks you expected to run and which were up-to-date (or from-cache?)?

My bad, I messed up the example and thought it was some caching issue. To showcase the problem, I created a simple sample: `sample/example-flavor`. It has two flavors in the `environment` dimension and the `staging` flavor overrides the launcher icons. Try `example-flavor:installStagingAaaDebug` without the fix (second commit) and the app icon will be the green one from the `main` source set. After the fix, the correct icon from the `staging` source set is taken.

My understanding of how the different ways of specifying app icons work together was too weak to integrate it into the `example-custom` sample.

**Comment by mateuszkwiecinski** [comment]
>Thanks! I tried to run the recordAll task, but it failed with this error: Failed to create the directory /sdcard/screenshots/com.example.flavor.productionAaaDebug.test/screenshots-default for screenshots. Is your sdcard directory read-only?. Are there any other preconditions I need to fulfill?

Screenshots require very specific setup to be recorded:
1. They require python with specific version of Pillow installed: https://github.com/usefulness/easylauncher-gradle-plugin/blob/d5bc16d6836e598efe1d87eff49542d8fa620bd5/.github/workflows/default.yml#L192
2. They require specific device to be installed: https://github.com/usefulness/easylauncher-gradle-plugin/blob/d5bc16d6836e598efe1d87eff49542d8fa620bd5/.github/workflows/default.yml#L199 or https://github.com/usefulness/easylauncher-gradle-plugin/blob/d5bc16d6836e598efe1d87eff49542d8fa620bd5/sample/emulator_config.ini

Your error suggests you tried to run it on api >28 device which is well... not yet supported :/ I have a plan to migrate to [paparazzi](https://github.com/cashapp/paparazzi/) at some point, but last time I checked it was not yet stable. 

>My understanding of how the different ways of specifying app icons work together was too weak to integrate it into the example-custom sample.

I think the only missing part was the fact all the pngs you added are used on api <26 devices only, and you were missing an override for adaptive icons. I merged `example-flavor` with `example-custom` and added missing color resource override. I hope it will pass the test. 

Regarding the fix itself, it was an obvious bug, thanks for fixing it 👍 
I believe taking a `variant.flavorName` into account could also be considered a bug, since such setup is _too specific_ and the generated icons will have lower priority than the "real" ones. I decided to keep it as it is, until someone complains 🤷

**Comment by mtrakal** [comment]
Hi, @mateuszkwiecinski do you plan new release soon? 🙏 I just today faces to this merged (not released yet) issue :).
Thanks a lot for your work on this plugin 👍

**Comment by mateuszkwiecinski** [comment]
Hey 👋  right, sorry for the delay 😞  
I will try to trigger a release today. I need first to verify if build configuration changes I had to make recently didn't break release pipeline.

**Pull request merged**
